Added support for bigint in ClassNameValue type
dcastil/tailwind-merge pull request #402
Opened 2024-04-18 01:46 UTC by LarsArtmann

2024-04-18 07:09 UTC, dcastil requested changes
Thanks for your PR! Just needs a small change.

2024-04-18 07:09 UTC, dcastil commented on src/lib/tw-join.ts
> +export type ClassNameValue = ClassNameArray | string | null | undefined | 0 | false | bigint
Only falsy bigints should be allowed here. Could you change it to only allow `0n` instead?

2024-04-19 04:13 UTC, LarsArtmann commented
Should be fine now.

2024-04-19 10:54 UTC, dcastil approved these changes
:rocket:

2024-04-19 10:55 UTC, merged